; CreditsTextPointers indexes (see data/credits/credits_text.asm)
	const_def
	const CRED_VERSION        ; $00
	const CRED_TAJIRI         ; $01
	const CRED_TA_OOTA        ; $02
	const CRED_MORIMOTO       ; $03
	const CRED_WATANABE       ; $04
	const CRED_MASUDE         ; $05
	const CRED_NISINO         ; $06
	const CRED_SUGIMORI       ; $07
	const CRED_NISHIDA        ; $08
	const CRED_MIYAMOTO       ; $09
	const CRED_KAWAGUCHI      ; $0A
	const CRED_ISHIHARA       ; $0B
	const CRED_YAMAUCHI       ; $0C
	const CRED_ZINNAI         ; $0D
	const CRED_HISHIDA        ; $0E
	const CRED_SAKAI          ; $0F
	const CRED_YAMAGUCHI      ; $10
	const CRED_YAMAMOTO       ; $11
	const CRED_TANIGUCHI      ; $12
	const CRED_NONOMURA       ; $13
	const CRED_FUZIWARA       ; $14
	const CRED_MATSUSIMA      ; $15
	const CRED_TOMISAWA       ; $16
	const CRED_KAWAMOTO       ; $17
	const CRED_KAKEI          ; $18
	const CRED_TSUCHIYA       ; $19
	const CRED_TA_NAKAMURA    ; $1A
	const CRED_YUDA           ; $1B
	const CRED_MON            ; $1C
	const CRED_DIRECTOR       ; $1D
	const CRED_PROGRAMMERS    ; $1E
	const CRED_CHAR_DESIGN    ; $1F
	const CRED_MUSIC          ; $20
	const CRED_SOUND_EFFECTS  ; $21
	const CRED_GAME_DESIGN    ; $22
	const CRED_MONSTER_DESIGN ; $23
	const CRED_GAME_SCENE     ; $24
	const CRED_PARAM          ; $25
	const CRED_MAP            ; $26
	const CRED_TEST           ; $27
	const CRED_SPECIAL        ; $28
	const CRED_PRODUCERS      ; $29
	const CRED_PRODUCER       ; $2A
	const CRED_EXECUTIVE      ; $2B
	const CRED_TAMADA         ; $2C
	const CRED_SA_OOTA        ; $2D
	const CRED_YOSHIKAWA      ; $2E
	const CRED_TO_OOTA        ; $2F
	const CRED_US_STAFF       ; $30
	const CRED_US_COORD       ; $31
	const CRED_TILDEN         ; $32
	const CRED_KAWAKAMI       ; $33
	const CRED_HI_NAKAMURA    ; $34
	const CRED_GIESE          ; $35
	const CRED_OSBORNE        ; $36
	const CRED_TRANS          ; $37
	const CRED_OGASAWARA      ; $38
	const CRED_IWATA          ; $39
	const CRED_IZUSHI         ; $3A
	const CRED_HARADA         ; $3B
	const CRED_MURAKAWA       ; $3C
	const CRED_FUKUI          ; $3D
	const CRED_CLUB           ; $3E
	const CRED_PAAD           ; $3F
	const CRED_NOVA			  ; $40
	const CRED_PROGRAMMER	  ; $41
	const CRED_ZETAPHOENIX    ; $42
	const CRED_PROGRAMMING_H  ; $43
	const CRED_ARIAHIRO		  ; $44
	const CRED_BLUEZANGOOSE   ; $45
	const CRED_DANNYE		  ; $46
	const CRED_DEVOLOV        ; $47
	const CRED_ENGEZERSTORUNG ; $48
	const CRED_JOJOBEAR       ; $49
	const CRED_LUNA           ; $4A
	const CRED_MATEO          ; $4B
	const CRED_MAUVE          ; $4C
	const CRED_MORD           ; $4D
	const CRED_RMP            ; $4E
	const CRED_RANGI          ; $4F
	const CRED_STM            ; $50
	const CRED_SOLUKU         ; $51
	const CRED_VORTIENE       ; $52
	const CRED_XILLICIS       ; $53
	const CRED_LEAD_ART		  ; $54
	const CRED_SUUNZ		  ; $55
	const CRED_ADDITIONAL_ART ; $56
	const CRED_AXEL_COMICS    ; $57
	const CRED_DREAMMAKER     ; $58
	const CRED_ESSENTURES     ; $59
	const CRED_NINBOY         ; $5A
	const CRED_PAT            ; $5B
	const CRED_RAINBOWDEVS    ; $5C
	const CRED_UTYTFT         ; $5D
	const CRED_WITTYCROW      ; $5E
	const CRED_YOELLISTRATOR  ; $5F
	const CRED_PARTY_MENU_I   ; $60
	const CRED_BLUE_EMERALD   ; $61
	const CRED_CHAMBER        ; $62
	const CRED_LAKE			  ; $63
	const CRED_NESLUG         ; $64
	const CRED_PIKACHU25      ; $65
	const CRED_RYTA           ; $66
	const CRED_SOLOO          ; $67
	const CRED_GSC_GRAPHICS   ; $68
	const CRED_GSC_G_DESIGN   ; $69
	const CRED_YOSHIDA        ; $6A
	const CRED_OKUTANI        ; $6B
	const CRED_IWASHITA       ; $6C
	const CRED_MONSTERS_1     ; $6D
	const CRED_MONSTERS_2     ; $6E
	const CRED_MONSTERS_3     ; $6F
	const CRED_MONSTERS_4     ; $70
	const CRED_POKERED_CONT   ; $71
	const CRED_KANZURE		  ; $72
	const CRED_IIMARCKUS      ; $73
	const CRED_YENATCH        ; $74
	const CRED_MANY_MORE      ; $75
	const CRED_BIG_YELLOW     ; $76
	const CRED_LYRA_WEBSITE   ; $77
	const CRED_PRET_DISCORD   ; $78
	const CRED_RETRO_GAME_1   ; $79
	const CRED_RETRO_GAME_2   ; $7A
	const CRED_SAGEDEOXYS     ; $7B
	const CRED_TESTING		  ; $7C
	const CRED_CHRIS05		  ; $7D
	const CRED_HYD            ; $7E
	const CRED_OBLIVION_WING  ; $7F
	const CRED_PATOMAREADO    ; $80
	const CRED_PK87           ; $81
	const CRED_THE_WISE_BRO   ; $82
DEF NUM_CRED_STRINGS EQU const_value

	const_def -1, -1
	const CRED_TEXT_FADE_MON ; $FF
	const CRED_TEXT_MON      ; $FE
	const CRED_TEXT_FADE     ; $FD
	const CRED_TEXT          ; $FC
	const CRED_COPYRIGHT     ; $FB
	const CRED_THE_END       ; $FA
